export const productDataList = [
  {
    id: 1,
    title: "Fjallraven",
    quantity: 1,
    price: "$249.21",
    sizes: ["X", "XXL"],
  },
  {
    id: 2,
    title: "Mens Casual T-Shirts",
    quantity: 1,
    price: "$343.43",
    sizes: ["XXL", "XL", "S"],
  },
  {
    id: 3,
    title: "Mens Cotton Jacket",
    quantity: 1,
    price: "$19.82",
    sizes: ["M", "S"],
  },
  {
    id: 4,
    title: "Mens Casual Slim",
    quantity: 1,
    price: "$263.02",
    sizes: ["X", "M", "S"],
  },
  {
    id: 5,
    title: "Chain Bracelet",
    quantity: 1,
    price: "$44.21",
    sizes: ["XXL", "XL", "S"],
  },
  {
    id: 6,
    title: "Solid Gold",
    quantity: 1,
    price: "$352.37",
    sizes: ["X", "XXL", "XL", "M"],
  },
  {
    id: 7,
    title: "Skirt",
    quantity: 1,
    price: "$192.72",
    sizes: ["X", "XXL", "XL"],
  },
  {
    id: 8,
    title: "British Cap",
    quantity: 1,
    price: "$131.06",
    sizes: ["X", "XL", "M", "S"],
  },
  {
    id: 9,
    title: "Polo Shirts",
    quantity: 1,
    price: "$300.53",
    sizes: ["X", "XXL", "M", "S"],
  },
  {
    id: 10,
    title: "Zara jeans",
    quantity: 1,
    price: "$87.14",
    sizes: ["X", "XXL", "XL", "S"],
  },
];
